### ISSUE TITLE
Strange issue with paging queries, sometimes it loads everything

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#597] opened 2022-11-15 16:26 UTC
I have a client which runs tests agains my server. I am using paged queries. I sometimes have the problem where the paging does _not_ work.

- Client sends requests inside test
- Page size is set to 3, while scylla has 4 rows
- **All 4 rows are returned**

This happens 1 out of 10 times. After it happened, **it keeps happening if I don't restart the server**, it looks like some kind of caching issue. I was hoping maybe someone knows if this is a default scylla optimization because the page size is so small, but then I would expect it to happen more often.

When I restart my server, the page size is working correctly and returns 3 rows, as configured. That is why I am thinking it is a driver bug, rather than a Scylla bug.

**Comment by piodul** [comment] 2022-11-15 17:04
Would you be able to prepare a reproducer? Which DB/driver version are you using?

In general, the CQL protocol does not guarantee that returned pages will be of requested size (see [here](https://github.com/scylladb/scylla-tools-java/blob/caf754f2434a55ad04e9dd147b8d97c62b8d8427/doc/native_protocol_v4.spec#L1034-L1040)). What you describe sounds more like something caused by the DB, but I'm not too familiar with nuances of how Scylla's paging works so I can't explain what is happening here without more information.

**Comment by Jasperav** [comment] 2022-11-15 17:18
@piodul I am trying to, but it just happens so randomly... But again: when it happens, I can reproduce the problem consistently by just executing the client's test and the problem goes away for a long time when I restart the server. I am using Catalytic which uses Scylla 0.6.1. 

I just hope that if I got a million rows and I am paging with 30, it will return a million rows. When I got the problem again, what steps can I take to provide debugging information for you?

**Comment by piodul** [comment] 2022-11-15 19:40
Hmm, Catalytic uses the CachingSession, right?

I can see that Catalytic calls `CachingSession::execute` in one place ([here](https://github.com/Jasperav/Catalytic/blob/1904671e946375071991e67ab06bf96423017a7d/catalytic/src/query_transform.rs#L230)) and `CachingSession::execute_iter` in the other ([here](https://github.com/Jasperav/Catalytic/blob/1904671e946375071991e67ab06bf96423017a7d/catalytic/src/query_transform.rs#L248)). In the first case it doesn't set the page size at all, and in the other one it sets the page to some number.

It looks like the CachingSession, in case when the query is already in the cache, it does not take the configuration of the query from the argument, but rather the configuration of the query which is already in the cache. Ref: https://github.com/scylladb/scylla-rust-driver/blob/61ba714d9917809b2bb1c2bd183e13554538adf7/scylla/src/transport/caching_session.rs#L147

My theory is: you first executed the path with `execute_iter` which stored the `Query` object with the right page size, but at some point it gets removed from the cache and the path that calls `execute` re-prepares it, but does not set the page size. I think that in this case `execute_iter` will use the default query size, which is 5000 rows.

I will send a fix for this tomorrow - so that `CachingSession::execute` will use the configuration of the query provided as a parameter.

While I can't be 100% sure, this is the likely cause. Maybe you could try reproducing this issue by sending a large number of queries with unique strings, then exercise the `execute` path and then try to use `execute_iter`. However, I'm not sure if it will work because I'm not sure how CachingSession chooses the elements to remove from the cache.

**Comment by Jasperav** [comment] 2022-11-15 21:15
@piodul This is it! Finally! I scratched my head over this for hours already like a year ago and decided to just let it go, but it turns out this is a nasty bug :(. I verified on my own project that the following code fails, although it should succeed:

```
#[tokio::test(flavor = "multi_thread")]
async fn test_temp() {
    let mut test_setup = TestSetup::setup().await;

    // Make sure no users are present
    entities::user::truncate(&test_setup.session).await.unwrap();

    // Generate a random user and insert it
    test_setup.generate_user().await;
    test_setup.generate_user().await;

    // Page with page size of 1 user
    let result = entities::user::select_all_qv()
        .select_paged(&test_setup.session, Some(1), None)
        .await
        .unwrap();

    assert_eq!(1, result.entities.len());

    // Page with page size of 2 users
    let result = entities::user::select_all_qv()
        .select_paged(&test_setup.session, Some(2), None)
        .await
        .unwrap();

    // This actually fails, although it should ofcourse succeed!
    assert_eq!(2, result.entities.len());
}
```

**Comment by piodul** [comment] 2022-11-16 11:16
> Is a `PreparedStatement` attached to a page size?

Page size is a part of the `PreparedStatement`, but only on the driver side. The database only needs the query string to prepare a query and returns an ID of the query and some metadata. IMO `CachingSession` should only cache the ID and metadata and not page size, consistency, etc. as those parameters are provided in `Query` passed to `execute`/`execute_iter`/etc.

**Closed** 2022-11-17 22:13 UTC

**Comment by Jasperav** [comment] 2022-11-22 10:26
@piodul can you please update the scylla version so I can use it in Catalytic?
