### ISSUE TITLE
`transport::cql_types_test::test_naive_date`: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-rust-driver#991] opened 2024-04-25 13:59 UTC
Scylla version: `5.5.0~dev`
Rust driver version: `v0.11.1`

Test failure 
```
transport::cql_types_test::test_naive_date

Stacktrace
Unique name: test_rust_1714047753_9
thread 'transport::cql_types_test::test_naive_date' panicked at scylla/src/transport/cql_types_test.rs:206:48:
called `Option::unwrap()` on a `None` value
```

Job: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-rust-driver-matrix/153/

Argus: https://argus.scylladb.com/test/bd78a051-9bdd-4f70-b554-b881cd3cf1b7/runs?additionalRuns[]=c50639c2-08d2-493f-84b0-b86b766589bb

**Comment by wprzytula** [comment] 2024-04-26 06:06
This is caused by https://github.com/scylladb/scylla-rust-driver/issues/917. The fix wasn't backported to 0.11.1, that's why the error persists.

**Comment by Lorak-mmk** [comment] 2024-04-26 07:22
It's worth noting that it's strictly an issue in the tests - there is no bug in the driver itself.

**Comment by Lorak-mmk** [comment] 2024-04-26 07:25
You can work around it by using older version of chrono: `cargo update chrono --precise 0.4.31`

**Comment by wprzytula** [comment] 2024-05-14 08:54
@Lorak-mmk Can we close this? This is likely irrelevant to overwhelming majority of driver's users - those who are running tests are probably developping the driver, and they definitely develop it based on the newest version (not as ancient as 0.11.1).

**Closed** 2024-05-29 08:45 UTC
