### ISSUE TITLE
There are few tests that started to fail after `05/30/2024`

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-rust-driver#1018] opened 2024-06-23 08:46 UTC
There are few tests that started to fail after `05/30/2024` (I cannot say more precise).

**Rust driver version is `v0.11.1` -  7 failed tests**

1. Error: `Cannot create CDC log for a table test_rust_1719130821_5.tbl, because keyspace uses tablets`
```
    <testcase name="test_partitioner_name_caching" time="1.641731179" classname="v0.11.1.transport::caching_session::tests">
      <failure type="cargo test" message="failed transport::caching_session::tests::test_partitioner_name_caching">Unique name: test_rust_1719130821_5
thread 'transport::caching_session::tests::test_partitioner_name_caching' panicked at scylla/src/transport/caching_session.rs:604:14:
called `Result::unwrap()` on an `Err` value: DbError(Invalid, &quot;Cannot create CDC log for a table test_rust_1719130821_5.tbl, because keyspace uses tablets. See issue #16317.&quot;) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</failure>
    </testcase>
```

```
    <testcase name="test_table_partitioner_in_metadata" time="0.439998484" classname="v0.11.1.transport::session_test">
      <failure type="cargo test" message="failed transport::session_test::test_table_partitioner_in_metadata">Unique name: test_rust_1719130823_59
thread 'transport::session_test::test_table_partitioner_in_metadata' panicked at scylla/src/transport/session_test.rs:1703:10:
called `Result::unwrap()` on an `Err` value: DbError(Invalid, &quot;Cannot create CDC log for a table test_rust_1719130823_59.t, because keyspace uses tablets. See issue #16317.&quot;)
</failure>
    </testcase>
```

```
    <testcase name="test_prepared_partitioner" time="1.2909249059999999" classname="v0.11.1.transport::session_test">
      <failure type="cargo test" message="failed transport::session_test::test_prepared_partitioner">Unique name: test_rust_1719130823_52
thread 'transport::session_test::test_prepared_partitioner' panicked at scylla/src/transport/session_test.rs:1885:10:
called `Result::unwrap()` on an `Err` value: DbError(Invalid, &quot;Cannot create CDC log for a table test_rust_1719130823_52.t2, because keyspace uses tablets. See issue #16317.&quot;)
</failure>
    </testcase>
```

2. Error `Cannot use LightWeight Transactions for table test_rust_1719130823_40.tab: LWT is not yet supported with tablets`
```
    <testcase name="test_batch_lwts" time="2.2298936400000002" classname="v0.11.1.transport::session_test">
      <failure type="cargo test" message="failed transport::session_test::test_batch_lwts">Unique name: test_rust_1719130823_40
thread 'transport::session_test::test_batch_lwts' panicked at scylla/src/transport/session_test.rs:2443:76:
called `Result::unwrap()` on an `Err` value: DbError(Invalid, &quot;Cannot use LightWeight Transactions for table test_rust_1719130823_40.tab: LWT is not yet supported with tablets&quot;)
</failure>
    </testcase>
```

```
    <testcase name="if_lwt_optimisation_mark_offered_then_negotiatied_and_lwt_routed_optimally" time="4.273741422" classname="v0.11.1.lwt_optimisation">
      <failure type="cargo test" message="failed lwt_optimisation::if_lwt_optimisation_mark_offered_then_negotiatied_and_lwt_routed_optimally">Unique name: test_rust_1719130827_8
thread '&lt;unnamed&gt;' panicked at scylla/tests/integration/lwt_optimisation.rs:135:65:
called `Result::unwrap()` on an `Err` value: DbError(Invalid, &quot;Cannot use LightWeight Transactions for table test_rust_1719130827_8.t: LWT is not yet supported with tablets&quot;)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'lwt_optimisation::if_lwt_optimisation_mark_offered_then_negotiatied_and_lwt_routed_optimally' panicked at scylla/tests/integration/lwt_optimisation.rs:16:1:
explicit panic
</failure>
    </testcase>
```

3. Error `panicked at scylla/src/transport/session_test.rs`
```
    <testcase name="test_token_awareness" time="1.510331113" classname="v0.11.1.transport::session_test">
      <failure type="cargo test" message="failed transport::session_test::test_token_awareness">Unique name: test_rust_1719130823_61
thread 'transport::session_test::test_token_awareness' panicked at scylla/src/transport/session_test.rs:579:9:
assertion `left == right` failed
  left: 2
 right: 1
</failure>
    </testcase>
```

```
    <testcase name="test_iter_works_when_retry_policy_returns_ignore_write_error" time="0.576360016" classname="v0.11.1.transport::session_test">
      <failure type="cargo test" message="failed transport::session_test::test_iter_works_when_retry_policy_returns_ignore_write_error">Unique name: test_rust_1719130823_49
thread 'transport::session_test::test_iter_works_when_retry_policy_returns_ignore_write_error' panicked at scylla/src/transport/session_test.rs:2619:5:assertion failed: !retried_flag.load(Ordering::Relaxed)
</failure>
    </testcase>
```
[rust_results_v0.11.1.xml.log](https://github.com/user-attachments/files/15943893/rust_results_v0.11.1.xml.log)

**Rust driver version is `v0.12.0` -  7 failed tests** - same as described above failed test
[rust_results_v0.12.0.xml.log](https://github.com/user-attachments/files/15943903/rust_results_v0.12.0.xml.log)

[Argus run](https://argus.scylladb.com/test/9e1dd913-1c47-4ee1-81c9-ec5d063891bd/runs?additionalRuns[]=b8826f9e-9df8-4261-8687-80658f1503a1)

**Comment by juliayakovlev** [comment] 2024-06-23 08:46
Please, let me know should I separate the issues or those tests should be ignored

**Comment by wprzytula** [comment] 2024-06-23 11:38
It's on @Lorak-mmk, as it's tablet-related. It seems to be caused by tablets being now the default in Scylla 6.0.

**Comment by Lorak-mmk** [comment] 2024-06-23 11:54
Those failures are caused by Scylla making Tablets the default in 6.0 release.

`test_partitioner_name_caching`, `test_table_partitioner_in_metadata`, `test_prepared_partitioner`, `test_token_awareness`, `test_iter_works_when_retry_policy_returns_ignore_write_error`: Fixed by my tablet PR: https://github.com/scylladb/scylla-rust-driver/pull/937

`test_batch_lwts`, `if_lwt_optimisation_mark_offered_then_negotiatied_and_lwt_routed_optimally`: Fixed by Mikołaj PR with CI fixes: https://github.com/scylladb/scylla-rust-driver/pull/1011

So those failures are expected in 0.11 / 0.12, but should not happen in 0.13 / main.

**Comment by Lorak-mmk** [comment] 2024-06-23 11:59
Oops, correction: `test_batch_lwts`, `if_lwt_optimisation_mark_offered_then_negotiatied_and_lwt_routed_optimally` may fail with 0.13 because Mikołaj's PR was merged after the release.

**Comment by juliayakovlev** [comment] 2024-06-23 13:02
@Lorak-mmk thanks. Should we test 0.13 as well?

**Comment by Lorak-mmk** [comment] 2024-06-23 13:15
> @Lorak-mmk thanks. Should we test 0.13 as well?

Test 0.13 in matrix? Yes, we should probably test new versions, right?

**Comment by juliayakovlev** [comment] 2024-06-24 08:04
> > @Lorak-mmk thanks. Should we test 0.13 as well?
> 
> Test 0.13 in matrix? Yes, we should probably test new versions, right?

@Lorak-mmk what is exactly version number? v0.13.0?

**Comment by Lorak-mmk** [comment] 2024-06-24 08:21
Yes

**Comment by Lorak-mmk** [comment] 2024-06-24 13:41
I assume this can be closed (because all the mentioned tests are already fixed).

**Closed by Lorak-mmk** 2024-06-24 13:41 UTC
