### ISSUE TITLE
Hangs when using scylla in cluster

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#306] opened 2021-09-30 04:31 UTC
When I run Scylla in docker, it run fine with this code:

```
pub async fn create_connection() -> Session {
    let session = SessionBuilder::new()
        .known_node("127.0.0.1:19042")
        .build()
        .await
        .unwrap();

    session.use_keyspace("mykeyspace", false).await.unwrap();

    session
}
```

I ran docker with `docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla`. This works fine.

But when I use docker compose or docker with scylla cluster, things don't work. This is the log (it hangs):

```
INFO scylla::transport::session: Shard-aware port detected: 19042
DEBUG scylla::transport::cluster: Requesting topology refresh
```

This is my docker compose file:

```
version: '3.2'

services:
  b-scylla:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla
    volumes:
      - ./:/project
    ports:
      - 9042:9042
      - 19042:19042
      - 9160:9160

  b-scylla2:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla2
    command:
      - "--seeds=b-scylla"

  b-scylla3:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla3
    command:
      - "--seeds=b-scylla"
```

And I run it with `docker-compose up -d`. 

Alternatively, this will hang the code as well:

`docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla`
wait...
`docker run --name scylla2  --hostname scylla2 -d scylladb/scylla --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla)"`

**Comment by cvybhu** [comment] 2021-09-30 10:37
It could because:

* `b-scylla` node starts, becomes part of the cluster (`b-scylla`, `b-scylla2`, `bscylla3`)
* Driver connects to `127.0.0.1` (`b-scylla`), downloads information that other nodes in the cluster are `b-scylla2` and `b-scylla3` (or some ips inside docker network)
* Driver tries to connect to `b-scylla2` and `b-scylla3`, but can't reach them because they are ips inside docker network and the driver operates on host network
* Connecting hangs, because there is no timeout and for some reason we don't receive error from the system. https://github.com/scylladb/scylla-rust-driver/blob/69c664d13a650effaba6eb58e76e58c6a23a9add/scylla/src/transport/connection_keeper.rs#L191
* `USE KEYSPACE` must be sent on all connections before finishing, so it hangs at well because `ConnectionKeeper` didn't start responding to the use keyspace requests

Adding a `tokio::timeout` [here](https://github.com/scylladb/scylla-rust-driver/blob/69c664d13a650effaba6eb58e76e58c6a23a9add/scylla/src/transport/connection_keeper.rs#L191) for opening connection should fix this, although there is also some work by @piodul aiming to rewrite some of this code https://github.com/scylladb/scylla-rust-driver/pull/261

**Comment by cvybhu** [comment] 2021-09-30 10:49
argh, even with timeout it won't work, because `ConnectionKeeper` starts responding to `USE KEYSPACE` requests after connecting, and here it will never connect.

@piodul should I fix this or will your changes cover it?

We could add to CI a cluster where one node is not reachable by the driver, this would help avoid such issues in the future,

**Comment by Jasperav** [comment] 2021-09-30 11:27
@cvybhu Does the driver freeze when a node does not respond? Hmm... Creating a CI with a scylla cluster shouldn't be to hard (just use the docker compose file in this issue), but not sure how to make the node not responding

**Comment by piodul** [comment] 2021-09-30 12:18
I run the example and it looks like it hangs while the session is being created - it does not reach the call of `use_keyspace`. The issue is present both in `main` and my PR (#261). While the issue described in https://github.com/scylladb/scylla-rust-driver/issues/306#issuecomment-931202653 sounds legitimate, there might be another problem.

**Comment by piodul** [comment] 2021-09-30 12:45
Hmm... Actually, the problem doesn't reproduce for me - on Linux, at least. @cvybhu suggested adding an iptables rule so that the IPs assigned by docker are not reachable (e.g. `172.x.x.x`) and it caused the session connect to hang, but @Jasperav mentioned that `session.query()` worked for them... Perhaps it's another issue.

@Jasperav are you using Windows by any chance? I don't have access to my Windows machine right now, but I can try reproducing the issue when I get to it.

**Comment by Jasperav** [comment] 2021-09-30 13:03
@piodul It fails on my macbook, and I just ran this code on my windows:

```
    #[tokio::test]
    async fn it_worksx() {
        let session = SessionBuilder::new()
            .known_node(database_url())
            .build()
            .await
            .unwrap();

        println!("{:#?}", session.query("select * from keyspacee.doesntmatter", &[]).await);

        //session.use_keyspace("xxx", false).await.unwrap();
    }
```

This is the output:
```

Err(
    DbError(
        Invalid,
        "Keyspace keyspacee does not exist",
    ),
)
```

When I uncomment the use_keyspace, it hangs. So it hangs on both windows and macbook.

**Comment by Jasperav** [comment] 2021-09-30 14:27
@piodul @cvybhu it also hangs when using the most basic cluster possible:

```
docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla
docker run --name scylla2 --hostname scylla2 -d scylladb/scylla --seeds="$(docker inspect --format='{{ 
.NetworkSettings.IPAddress }}' scylla)"
```

**Comment by piodul** [comment] 2021-09-30 19:32
@Jasperav @cvybhu 

I ran the example on Windows and the issue reproduces - the session is created but it hangs on `use_keyspace`. I added some debug messages locally and I confirm @cvybhu's explanation from here: https://github.com/scylladb/scylla-rust-driver/issues/306#issuecomment-931202653.

I also ran the example with reworked logic from #261 and it does not hang. However, it takes it `connection_timeout` to create a session, and the same amount of time to run `use_keyspace`, then it fails with an error (keyspace not found). The timeout is 5s by default, so this is something which should be improved before the PR is merged.

**Comment by piodul** [comment] 2021-09-30 19:58
By the way, a fun fact: it looks like that Windows' Docker networking implementation translates source ports, and translated source ports are always even - this renders the shard-aware port connection mechanism ineffective (it never connects to odd shards on nodes with even number of shards).

Additionally, with #261, if you provide an address with a shard-aware port in the contact points, it will treat it as a non-shard-aware port and use it as a fallback. Combined with the source port translation described above, the new implementation will never manage to establish a connection per shard. This should also be fixed before merging.

**Comment by Jasperav** [comment] 2021-10-01 07:28
> I also ran the example with reworked logic from #261 and it does not hang. However, it takes it `connection_timeout` to create a session, and the same amount of time to run `use_keyspace`, then it fails with an error (keyspace not found). 

Does this mean the fix will be adding a connection timeout? Can this driver work with multiple nodes?

**Comment by piodul** [comment] 2021-10-01 09:01
@Jasperav

> Does this mean the fix will be adding a connection timeout? Can this driver work with multiple nodes?

Let me clarify: multiple nodes in the cluster isn't the issue. The problem is that only one node is reachable.

When you create a session, it connects to one of the nodes using the IP address you have provided in `known_node`. After successfully connecting it returns, but in the background it reads the `system.peers` table to learn about IPs of other nodes and then tries to connect to them using that IPs.

You forwarded ports `9042` and `19042` for the first container, so using `127.0.0.1:19042` as a known node address will successfully connect you to the first node. However, docker assigns custom IP addresses to containers - for example, on my machine they were as follows: `172.18.0.2` , `172.18.0.3`, `172.18.0.4`. Those addresses are put into `system.peers`, so the driver will try to connect to them.

It looks like on Linux those addresses starting with 172 are reachable, but on Windows they are not - I tried pinging them and it only worked on Linux, on Windows I got a timeout. I suspect there might be a similar issue on MacOS.

Could you check if you can ping the containers by their IPs? You can get the IP of a container like this:

    docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <name or ID of your container>

If they are not, then it's most likely the culprit. You should make sure that those IPs are reachable from your application if you want the driver to connect to all nodes.

----

As for what exactly is broken in the driver: `use_keyspace` hangs if it can't connect to some node.

Here are the nitty gritty details: when you call `use_keyspace`, a message is sent to each ConnectionKeeper (they are responsible for establishing connections and reconnecting if a connection is broken). However, the ConnectionKeeper can only handle `use_keyspace` messages if it has a working connection - if it is stuck trying to connect, it will not handle the `use_keyspace` message. The driver already has connection timeouts implemented but they do not help here.

I'll try to handle it in #261 (it partially does, as explained in my previous comments, I'll just try to lower the waiting time).

**Comment by roydahan** [comment] 2024-06-13 17:18
@wprzytula / @Lorak-mmk is this one still relevant?
I believe it can be closed.

**Comment by wprzytula** [comment] 2024-06-13 17:21
> @wprzytula / @Lorak-mmk is this one still relevant?
> I believe it can be closed.

@Jasperav does it still happen in the newest release of the driver? If so, please reopen.
Closing as stale.

**Closed** 2024-06-13 17:22 UTC
