### ISSUE TITLE
Unsupported types prevent driver from being used at all

### ISSUE THREAD

**Issue by nemosupremo** [scylladb/scylla-rust-driver#445] opened 2022-05-05 22:39 UTC
I tried to upgrade Scylla driver from a commit around 1aee7b25080a87225c011d22599650f4c3def692 to 0.4.4. I have a table that has a column defined as `map<int, frozen<map<text, int>>>` which is not supported by the driver. However this table was not used to accessed by my project.

Upon upgrading, connecting to the cluster crashes with: `Invalid message: type map<int, frozen<map<text, int>>> is not implemented`.

**Comment by piodul** [comment] 2022-05-06 04:27
This is most likely a duplicate of https://github.com/scylladb/scylla-rust-driver/issues/437, it was fixed in https://github.com/scylladb/scylla-rust-driver/commit/46d605ea80e9d6813c63c2c97db8ec6dcc82115a (not yet a part of any release). Could you check if it fixes the issue for you?

**Closed** 2022-05-06 05:02 UTC

**Comment by psarna** [comment] 2022-05-06 05:44
I'll push 0.4.5 today to avoid more issues like that
